# DNSé˜²æ³„éœ²ç‰ˆæœ¬
# å¿…è¯»ï¼ï¼ï¼
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…
# proxy-providersä¸‹çš„ interval: 604800  å•ä½ä¸ºç§’  604800å¯¹åº”7å¤©
proxy-providers:
  Airport1:
    url: "https://drfytjmjhggnrgergergergerg6555.saojc.xyz/api/v1/client/subscribe?token=262ffa4b0a2b2159ca1279e024dadf32"
    type: http
    interval: 604800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    proxy: ç›´è¿

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿, type: direct}
  # - {name: ç›´è¿, type: direct, udp: true}

# å…¨å±€é…ç½® 
mixed-port: 7890
# socks-port: 7891
# redir-port: 7892
# tproxy-port: 7894
# port: 7893
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
# interface-name: enxc8a3622b418d (æ ¹æ®æƒ…å†µæŒ‡å®šå‡ºç«™æ¥å£ï¼Œä¸€èˆ¬ä¸éœ€è¦)
# authentication  (ä»£ç†ç”¨æˆ·éªŒè¯ä¿¡æ¯)
#   - name: password
log-level: warning
# åŒ¹é…è¿›ç¨‹ always/strict/off
find-process-mode: always
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# ä¸ºé˜²æ­¢ä½¿ç”¨æ’ä»¶æœ‹å‹é‡åˆ°é¢æ¿é—®é¢˜ï¼Œæˆ‘æ³¨é‡Šæ‰äº†æ­¤æ¨¡å—ã€‚
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# external-ui-name: metacubexd
# external-ui-url: "https://github.com/MeteCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
# external-ui-name: yacd-meta
# external-ui-url: "https://github.com/MeteCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip"

# å—…æ¢ï¼ˆfakeipä¸‹å…¶å®å¯ä»¥ä¸ç”¨å—…æ¢ï¼‰
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.push.apple.com"

# å…¥ç«™
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #ä½¿ç”¨nikkiï¼Œæ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
  #device: nikki
  #ä½¿ç”¨ä»…å†…æ ¸è‡ªè¡Œä¿®æ”¹ä¸‹é¢ä¸‰é¡¹ä¸ºtrue
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNSæ¨¡å—
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: false
  # respect-rules: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  # default-nameserver:
  #   - https://223.5.5.5/dns-query
  # proxy-server-nameserver:
  #   - https://dns.alidns.com/dns-query
  #   - https://doh.pub/dns-query
  # direct-nameserver:
  #   - https://dns.alidns.com/dns-query
  #   - https://doh.pub/dns-query
  # nameserver:
  #   - https://8.8.8.8/dns-query#RULES&ecs=223.5.5.0/24
  nameserver:
    - 192.168.31.1
  fake-ip-filter:
    - "rule-set:fakeipfilter_domain"
 
# å‡ºç«™ç­–ç•¥ï¼Œæ ¹æ®è‡ªå·±æƒ…å†µè°ƒæ•´æ¯ä¸ªç­–ç•¥é‡Œåˆ†ç»„æ’åºï¼Œå¢åˆ éƒ½å¯ä»¥ï¼Œæ¯”å¦‚æŠŠç¾å›½è‡ªåŠ¨æ”¾åˆ°ç¬¬ä¸€ä¸ªï¼Œæ¯”å¦‚åˆ é™¤é¦™æ¸¯æ•…è½¬ï¼Œæ³¨æ„åˆ«æ¼æ‰è¡¨æƒ…é€—å·ç­‰ã€‚
# å¦‚æœç›¸åº”åˆ†ç»„æ²¡æœ‰ç­›é€‰åˆ°å¯¹åº”çš„å›½å®¶ï¼Œè¯·æ ¹æ®è‡ªå·±èŠ‚ç‚¹åå­—è°ƒæ•´ç­›é€‰å…³é”®å­—ã€‚
# æ²¡æœ‰å†ä½¿ç”¨é”šç‚¹ï¼Œæ˜¯è€ƒè™‘å¾ˆå¤šæ–°æ‰‹ä¿®æ”¹éš¾åº¦ï¼Œè¿™æ ·æ–°æ‰‹ä¿®æ”¹æŸä¸ªåˆ†ç»„æ›´å®¹æ˜“äº›ã€‚
proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸµ TikTok, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ“¹ YouTube, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ€ Google, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ¤– ChatGPT, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ¬ OneDrive, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸªŸ Microsoft, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ“² Telegram, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ¥ NETFLIX, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ’¶ PayPal, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ç›´è¿]}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|éŸ©|æ–°|æ—¥)).)*$"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(å°|æ—¥|éŸ©|æ·±|ç¾)).)*$"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$"}
  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, interval: 600, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ”¯ ç¾å›½æ•…è½¬, type: fallback, include-all: true, interval: 600, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|éŸ©|æ–°|æ—¥)).)*$"}
  - {name: ğŸ”¯ ç‹®åŸæ•…è½¬, type: fallback, include-all: true, interval: 600, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(å°|æ—¥|éŸ©|æ·±|ç¾)).)*$"}
  - {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬, type: fallback, include-all: true, interval: 600, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$"}
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 200, interval: 600, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 200, interval: 600, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ ç‹®åŸè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 200, interval: 600, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|ç¾)).)*$"}
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 200, interval: 600, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 200, interval: 600, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}

# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,private_domain,ç›´è¿
  - SRC-IP-CIDR,172.17.0.4/32,ç›´è¿
  - RULE-SET,diy_direct,ç›´è¿
  - RULE-SET,banad,REJECT
  - RULE-SET,banprogramad,REJECT
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,apple_domain,ç›´è¿
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - DOMAIN-SUFFIX,qichiyu.com,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,apple_ip,ç›´è¿,no-resolve
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,cn_ip,ç›´è¿,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
# å¦‚æœéœ€è¦åœ¨openclashæ’ä»¶ä¸­ä½¿ç”¨ï¼Œé”šç‚¹ä½¿ç”¨æ–¹å¼å¯èƒ½éœ€è¦ç”± "<<:" æ”¹ä¸º "!!merge <<:"
rule-providers: 
  diy_direct: { <<: *class, url: "https://raw.githubusercontent.com/TrevorLeeXOR/clashconfig/refs/heads/main/DIY_DIRECT.list"}

  banad: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"}
  banprogramad: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"}

  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  ai: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
